version: '3'

services:
  yana-django:
    ports:
    - "${YANA_OUTSIDE_PORT_FRONT}:80"
    - "${YANA_OUTSIDE_PORT_BACK}:81"
    image: "yana:latest"
    env_file:
      - .env
    depends_on:
      - yana-postgres


  yana-postgres:
    ports:
    - "${PG_OUTSIDE_PORT}:5432"
    env_file:
    - .env
    image: "postgres:15-alpine"
